---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Oracle Linux)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "OracleLinux"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for Ubuntu
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php for Oracle Linux
    tags: apache, oraclelinux,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "OracleLinux"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Oracle Linux)
    tags: oraclelinux,mariadb
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "OracleLinux"

  - name: install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_server
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
