  - name: install apache and php for Ubuntu
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php for Oracle Linux
    tags: apache, oraclelinux,httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "OracleLinux"

  - name: start httpd (Oracle Linux)
    tags: apache, oraclelinux, https
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "OracleLinux"

  - name: change e-mail address for admin
    tags: apache, OracleLinux, httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
    when: ansible_distribution == "OracleLinux"
    register: httpd

  - name: restart httpd (Oracle Linux)
    tags: apache, OracleLinux, httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
